name: bittorrent_dht
description: A DHT protocal implemented by Dart. This package implemented BEP-0005 for torrent client
version: 0.0.11
repository: https://github.com/moham96/bittorrent_dht
issue_tracker: https://github.com/moham96/bittorrent_dht/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  b_encode_decode: ^1.0.4
  dtorrent_common: ^1.0.5
  meta: ^1.9.1
  events_emitter2: ^1.0.3
  collection: ^1.17.0
dev_dependencies:
  lints: ^2.0.1
  logging: ^1.2.0
  test: ^1.24.3
  dtorrent_parser: ^1.0.8
  analyzer: any
